const constants = {
	TOGGLE_MODAL: "TOGGLE_MODAL",
	SAVE_DOCTOR_AVAILABILITY:"SAVE_DOCTOR_AVAILABILITY",
	SAVE_ASSISTANT_AVAILABILITY:"SAVE_ASSISTANT_AVAILABILITY",
	SAVE_HIGENIST_AVAILABILITY:"SAVE_HIGENIST_AVAILABILITY",
	CLOSE_MODAL:"CLOSE_MODAL"
}

export default constants